apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm-load-balancer
  namespace: projeto
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "nginx-phpfpm-load-balancer"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-name: "cert-k8s"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-http-idle-timeout-seconds: "240"
    # service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
spec:
  type: LoadBalancer
  selector:
    app: nginx-phpfpm
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: nginx-port
    - name: https
      protocol: TCP
      port: 443
      targetPort: nginx-port
