apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm-deployment
  namespace: projeto
spec:
  selector:
    matchLabels:
      app: nginx-phpfpm
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      imagePullSecrets:
        - name: registry-dohub
      containers:
        - name: nginx-phpfpm
          image: registry.digitalocean.com/dohub/maurouberti/nginx:latest
          ports:
            - name: nginx-port
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: nginx-phpfpm-configmap
