apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: projeto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: projeto
stringData:
  MYSQL_ROOT_PASSWORD: "123456"
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: projeto
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: mysql-port
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: projeto
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: registry-dohub
      containers:
        - name: mysql
          image: registry.digitalocean.com/dohub/maurouberti/mysql:latest
          ports:
            - name: mysql-port
              containerPort: 3306
          args:
            - "--innodb_use_native_aio=0"
            - "--default-authentication-plugin=mysql_native_password"
            - "--table_definition_cache=1024"
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
