apiVersion: v1
kind: ConfigMap
metadata:
  name: phpfpm-configmap
  namespace: projeto
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_DATABASE: "apresentacao"
  DB_USERNAME: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: phpfpm-secret
  namespace: projeto
data:
  DB_PASSWORD: "MTIzNDU2" # 123456
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-service
  namespace: projeto
spec:
  type: ClusterIP
  selector:
    app: phpfpm
  ports:
    - port: 9000
      targetPort: phpfpm-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-deployment
  namespace: projeto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      imagePullSecrets:
        - name: registry-dohub
      containers:
        - name: phpfpm
          image: registry.digitalocean.com/dohub/maurouberti/php-fpm:latest
          ports:
            - name: phpfpm-port
              containerPort: 9000
          envFrom:
            - secretRef:
                name: phpfpm-secret
            - configMapRef:
                name: phpfpm-configmap
          resources:
            requests: # Um request é o valor mínimo de recursos que o container precisa para ser agendado (scheduled) em um node.
              cpu: "100m"   # Solicita 100 milicores de CPU (Solicita 0.1 vCPU)
              memory: "128Mi"  # Solicita 256 Megabytes de memória (Solicita 512 MiB de memória)
            limits: # O limit é o valor máximo de recursos que o container pode consumir.
              cpu: "1000m" # Limite máximo de CPU para o contêiner (Limita em 1 vCPU)
              memory: "1024Mi" # Limite máximo de memória para o contêiner (Limita em 1 GiB)
---