apiVersion: v1
kind: Secret
metadata:
  name: registry-dohub
  namespace: projeto
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.digitalocean.com": {
          "username": "usuario-do@email.com",
          "password": "SEU-TOKEN",
          "email": "usuario-do@email.com"
        }
      }
    }
