---
- name: Instalação do Servidor
  hosts: all
  vars_files:
    - vars.yaml
  become: true
  tasks:

    - name: 1/15 - Atualizar a lista de pacotes
      ansible.builtin.apt:
        update_cache: true

    - name: 2/15 - Instalar pacotes
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-docker # community.docker
          - python3-gitlab # community.general.gitlab_runner
          - unrar
          - git
        state: present

    - name: 3/15 - Instalar pacotes Python
      ansible.builtin.pip:
        name:
          - s3cmd
          - boto3
          - botocore
        break_system_packages: true
        state: present

    - name: 4/15 - Verificar se o arquivo /projeto/docker-compose.yaml existe no droplet
      ansible.builtin.stat:
        path: /projeto/docker-compose.yaml
      register: www_status

    - block:

        - name: 5/15 - Remover pacotes Docker
          ansible.builtin.package:
            name:
              - docker.io
              - docker-doc
              - docker-compose
              - docker-compose-v2
              - podman-docker
              - containerd
              - runc
            state: absent

        - name: 6/15 - Baixar o script de instalacao do Docker
          ansible.builtin.get_url:
            url: https://get.docker.com
            dest: /tmp/get-docker.sh
            mode: "0755"

        - name: 7/15 - Executar o script de instalacao do Docker
          ansible.builtin.shell: sh /tmp/get-docker.sh

      when: not www_status.stat.exists # Executar tarefa apenas se o arquivo /projeto/docker-compose.yaml não existir



    - name: 8/15 - Garantir que a rede externa 'network_projeto' existe
      community.docker.docker_network:
        name: network_projeto
        driver: bridge
        state: present
        # external: true  # Especifica que a rede é externa

    - name: 9/15 - Carregar token do arquivo
      set_fact:
        digitalocean_token: "{{ lookup('file', '../../tokens/doctl-access-token') }}"

    - name: 10/15 - Autenticar no registry do DigitalOcean
      community.docker.docker_login:
        registry_url: "https://registry.digitalocean.com"
        username: "{{ email }}"
        password: "{{ digitalocean_token }}"
      register: docker_login_result

    - name: Verificar sucesso da autenticação
      debug:
        msg: "Autenticação no registry foi bem-sucedida: {{ docker_login_result }}"



    - name: 11/15 - Instalar certbot
      ansible.builtin.apt:
        name:
          - certbot
        state: present
        update_cache: true

    - name: 12/15 - Obter certificado SSL com Certbot em modo standalone
      command: certbot certonly --standalone -d {{ domain }} --non-interactive --agree-tos --email {{ email }}



    - name: 13/15 - Criar diretorios
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/projeto"
        - "/projeto/apps"
        - "/projeto/apps/www"
        - "/projeto/apps/www/nginx"
        - "/projeto/config"
        - "/projeto/config/nginx"

    - name: 14/15 - Copiar diretorios e arquivos
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0755"
      loop:
        - { src: "docker-compose.yaml", dest: "/projeto/docker-compose.yaml"}
        - { src: "config/nginx/nginx.conf", dest: "/projeto/config/nginx/nginx.conf"}
        - { src: "config/nginx/locust_1.conf", dest: "/projeto/config/nginx/locust_1.conf"}
        - { src: "config/nginx/locust_2.conf", dest: "/projeto/config/nginx/locust_2.conf"}

    - name: 15/15 - Iniciar containers
      community.docker.docker_compose_v2:
        project_src: "/projeto/"
        files:
          - "/projeto/docker-compose.yaml"
        state: present
