services:

  nginx:
    hostname: nginx
    container_name: nginx
    image: registry.digitalocean.com/dohub/maurouberti/nginx:latest
    volumes:
      - /projeto/apps/www/nginx:/var/www/html
      - /projeto/config/nginx:/etc/nginx/conf.d
      - /projeto/logs/nginx:/var/log/nginx
      - /etc/letsencrypt/live/dc.dominio.com.br/fullchain.pem:/etc/ssl/server.crt
      - /etc/letsencrypt/live/dc.dominio.com.br/privkey.pem:/etc/ssl/server.key
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "443:443"
      - "8001:8001"
    networks:
      - network_projeto

  phpfpm:
    hostname: phpfpm
    container_name: phpfpm
    image: registry.digitalocean.com/dohub/maurouberti/php-fpm:latest
    ports:
      - "9000:9000"
    networks:
      - network_projeto
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=apresentacao
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    depends_on:
      - mysql_db

  mysql_db:
    hostname: mysql_db
    container_name: mysql_db
    image: registry.digitalocean.com/dohub/maurouberti/mysql:latest
    volumes:
      - ./apps/mysql:/var/lib/mysql
      - ./config/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    networks:
      - network_projeto
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apresentacao

  locust:
    hostname: locust
    container_name: locust
    image: registry.digitalocean.com/dohub/maurouberti/locust:latest
    ports:
      - "8089:8089"
    networks:
      - network_projeto

networks:
  network_projeto:
    external: true
